---
title: "METE and succession"
author: "Andy Kleinhesselink"
date: 2019-05-05
categories: ["METE"]
tags: ["equilibrium", "succession", "METE"]
output:
  blogdown::html_page:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

There's something about ecological communities that has long fascinated me but that has been very difficult to put my finger on. A bare patch of ground in the middle of the forest will soon be colonized by saplings and over the course of a few years it will come to look much like the forest that surounds it. Even our cities, if not constantly weeded and maintained, would sprout weeds from the sidewalks, streets, and even the roofs of buildings. 

This process, ecological succession, seems to impose an order on nature but paradoxically it does so spontaneously. We rarely if ever observe the reverse: a forest spontaneously becoming a bare patch of ground.  To clear a forest to bare ground, takes a huge external influence--such as the energy of a storm, flood or fire.

Ecologists have long been tempted (cite), and I follow them here, to hypothesize that there is something intrinsically special about the state that ecosystems move towards through the process of succession.  While there have been many studies and descriptions of sucession in particular ecosystems, there is no truly general quantitative and predictive theory of succession--as far as I can tell.  

A major challenge to offering such a theory is in finding an objective way to differentiate a late successional state from all other possible states that an ecosystem could take. What can we measure about an ecosystem, short of observing its actual change over time, that would tell us the direction and speed of its change?  

Erica Newman and co-authors have recently published a provocative attempt to do just using the John Harte's Maximum Entropy Theory of Ecology (METE). Using data on post-fire succession in a California forest, they show that the METE can differentiate forests that were recently burned from forests that have not been burned for a long time.  What's important here is that the theory is not merely an ecosystem specific definition of succession--that is, the theory applies without measuring any ecosystem  specific parameters.  

How does it do this? 

I believe this question sits at the very heart of community ecology and that the answer has major practical implications for restoration ecology and predicting how ecosystems will respond to anthropogenic change.

